version: '2.2'

services:
  server:
    container_name: groc-server
    restart: always
    image: groc-server
    environment:
      - DATABASE_URL=mongodb://groc-db:27017/autogroc
    build:
      context: server
      dockerfile: dockerfile
    volumes:
      - ./server:/server/
    ports:
      - 5000:5000
    networks:
      - shared-network
    depends_on:
      - groc-db
    links:
      - groc-db

  client:
    container_name: groc-client
    restart: unless-stopped
    image: groc-client
    build:
      context: client
      dockerfile: dockerfile
    volumes:
      - ./client:/client/
    ports:
      - 80:80
    networks:
      - shared-network
    depends_on:
      - server
    links:
      - server:se

  groc-db:
    image : mongo
    container_name: groc-db
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - shared-network

networks:
  shared-network:
